import React, { useEffect, useRef } from 'react';
import * as BABYLON from '@babylonjs/core';
import { createLabEnvironment, createLabLighting, createLabCamera } from '../utils/labEnvironment';

const GenericSimulation = ({ settings, onUpdate, isRunning }) => {
    const canvasRef = useRef(null);
    const engineRef = useRef(null);
    const sceneRef = useRef(null);
    const objectRef = useRef(null);

    useEffect(() => {
        if (!canvasRef.current) return;

        const engine = new BABYLON.Engine(canvasRef.current, true);
        const scene = new BABYLON.Scene(engine);
        scene.clearColor = new BABYLON.Color4(0.01, 0.02, 0.04, 1);

        createLabEnvironment(scene);
        createLabLighting(scene);
        createLabCamera(scene, new BABYLON.Vector3(0, 2, 0), { radius: 15 });

        // Placeholder object
        const box = BABYLON.MeshBuilder.CreateBox("placeholder", { size: 2 }, scene);
        box.position.y = 2;
        const mat = new BABYLON.StandardMaterial("placeholderMat", scene);
        mat.diffuseColor = new BABYLON.Color3(0.2, 0.5, 1);
        mat.emissiveColor = new BABYLON.Color3(0.1, 0.2, 0.4);
        box.material = mat;
        objectRef.current = box;

        engineRef.current = engine;
        sceneRef.current = scene;

        engine.runRenderLoop(() => {
            if (scene) scene.render();
        });

        const resize = () => engine.resize();
        window.addEventListener("resize", resize);

        return () => {
            window.removeEventListener("resize", resize);
            engine.dispose();
        };
    }, []);

    useEffect(() => {
        const scene = sceneRef.current;
        if (!scene) return;

        const rotationStep = () => {
            if (isRunning && objectRef.current) {
                objectRef.current.rotation.y += 0.02;
                objectRef.current.rotation.x += 0.01;

                // Mock telemetry
                onUpdate({
                    status: "AI Generated",
                    rotation: (objectRef.current.rotation.y % (Math.PI * 2)).toFixed(2),
                    active: isRunning ? "YES" : "NO"
                });
            }
        };

        scene.onBeforeRenderObservable.add(rotationStep);
        return () => scene.onBeforeRenderObservable.removeCallback(rotationStep);
    }, [isRunning, onUpdate]);

    return (
        <div style={{ width: '100%', height: '100%', position: 'relative' }}>
            <canvas ref={canvasRef} style={{ width: '100%', height: '100%', outline: 'none' }} />
            <div style={{
                position: 'absolute',
                top: '50%',
                left: '50%',
                transform: 'translate(-50%, -50%)',
                textAlign: 'center',
                pointerEvents: 'none',
                background: 'rgba(0,0,0,0.6)',
                padding: '20px',
                borderRadius: '15px',
                border: '1px solid rgba(59, 130, 246, 0.3)',
                backdropFilter: 'blur(5px)'
            }}>
                <h2 style={{ color: '#3b82f6', marginBottom: '10px' }}>AI-Generated Lab</h2>
                <p style={{ color: '#94a3b8', fontSize: '14px' }}>
                    This simulation was dynamically generated by Nexus Brain.<br/>
                    A specialized 3D environment is being calibrated.
                </p>
                <div style={{ marginTop: '15px', fontSize: '12px', color: '#64748b' }}>
                    {Object.keys(settings).length > 0 ? 'Parameters received: ' + Object.keys(settings).join(', ') : 'No parameters defined'}
                </div>
            </div>
        </div>
    );
};

export default GenericSimulation;
